apiVersion: apps/v1
kind: Deployment
metadata:
    name: ecosite
spec:
    selector:
        matchLabels:
            app: ecosite
    replicas: 2
    template:
        metadata:
            labels:
                app: ecosite
        spec:
            containers:
                - name: ecosite-api
                  imagePullPolicy: Never
                  image: ecosite
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
    name: ecosite
spec:
    selector:
        app: ecosite
    ports:
        - port: 3030
          targetPort: 3030
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /tree
  name: ecositeingress
  labels:
    name: ecositeingress
spec:
  rules:
  - host: local.ecosia.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ecosite
            port: 
              number: 3030